name: Build and run unit tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm test
    - name: Build single script
      run: npm run build
    - name: Minify
      run: npm run minify
    - name: Commit bundled and minified files
      run: git commit -m "Adding changes from CI" -a  || echo "Nothing to update"
    - name: Push changes to branch that initiated PR
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
    
      env:
        CI: true
